name: Azle Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  basic-integration-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        azle_source:
          - npm
          - repo
        example_directories:
          - examples/complex_types
          - examples/counter
          - examples/cross_canister_calls
          - examples/generators
          - examples/heartbeat
          - examples/ic_api
          - examples/imports
          - examples/init
          - examples/inline_types
          - examples/key_value_store
          - examples/motoko_examples/calc
          - examples/motoko_examples/counter
          - examples/optional_types
          - examples/pre_and_post_upgrade
          - examples/primitive_types
          - examples/query
          - examples/simple_erc20
          - examples/simple_user_accounts
          - examples/stable_storage
          - examples/update
    steps:
      - uses: actions/checkout@v2
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - shell: bash -l {0}
        run: nvm install 14
      - run: DFX_VERSION=0.9.3 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Rust cache
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: ${{ matrix.example_directories }}/target
          key: ${{ matrix.example_directories }}-cache
          restore-keys: ${{ matrix.example_directories }}-cache # TODO might need to be more intelligent and hash files here
      - shell: bash -l {0}
        run: nvm use 14
      - shell: bash -l {0}
        run: npm install
      - if: matrix.azle_source == 'repo'
        shell: bash -l {0}
        run: npm link
      - working-directory: ${{ matrix.example_directories }}
        run: dfx start --clean --background
      - shell: bash -l {0}
        working-directory: ${{ matrix.example_directories }}
        run: npm install
      - if: matrix.azle_source == 'repo'
        shell: bash -l {0}
        working-directory: ${{ matrix.example_directories }}
        run: npm link azle
      - shell: bash -l {0}
        working-directory: ${{ matrix.example_directories }}
        run: npm test